// This file was generated by cz.syntea.xdef.component.GenXComponent.
// XDPosition: "N#Part".
// Any modifications to this file will be lost upon recompilation.
package test.xdef.component;

public interface N_i extends cz.syntea.xdef.component.XComponent {
  public Integer getOne();
  public void setOne(Integer x);
  public String xposOfOne();
  public String getTwo();
  public void setTwo(String x);
  public String xposOfTwo();
}