// This file was generated by org.xdef.component.GenXComponent.
// X-position: "A#Person".
// Any modifications to this file will be lost upon recompilation.
package task6.components2;

public interface Citizen extends org.xdef.component.XComponent {
  public String getFirstName();
  public void setFirstName(String x);
  public String xposOfFirstName();
  public String getLastName();
  public void setLastName(String x);
  public String xposOfLastName();
}