// This file was generated by org.xdef.component.GenXComponent.
// X-position: "C#Residents".
// Any modifications to this file will be lost upon recompilation.
package task6.components2;
@SuppressWarnings("unchecked")
public class Tenants implements org.xdef.component.XComponent {
  public java.util.List<Tenants.Resident> listOfResident() {
    return _Resident;
  }
  public void addResident(Tenants.Resident x) {
    if (x!=null) _Resident.add(x);
  }
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  private final java.util.List<Tenants.Resident> _Resident=new java.util.ArrayList<>();
  @Override
  public Object toXon() {return org.xdef.component.XComponentUtil.toXon(this);}
  @Override
  public org.w3c.dom.Element toXml()
    {return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
    String name, String ns, String xdPos) {
    XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return -1;}
  public static final byte XON = 0;
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
    java.util.List<org.xdef.component.XComponent> a=new java.util.ArrayList<>();
    org.xdef.component.XComponentUtil.addXC(a, listOfResident());
    return a;
  }
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
    org.w3c.dom.Element el;
    if (doc==null) {
      doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,XD_NodeName,null);
      el = doc.getDocumentElement();
    } else {
      el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
      if (doc.getDocumentElement()==null) doc.appendChild(el);
    }
    for (org.xdef.component.XComponent x: xGetNodeList())
      el.appendChild(x.toXml(doc));
    return el;
  }
  public Tenants() {}
  public Tenants(org.xdef.component.XComponent p,
    String name, String ns, String xPos, String XDPos) {
    XD_NodeName=name; XD_NamespaceURI=ns;
    XD_XPos=xPos;
    XD_Model=XDPos;
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
  }
  public Tenants(org.xdef.component.XComponent p,org.xdef.proc.XXNode x) {
    org.w3c.dom.Element el=x.getElement();
    XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
    XD_XPos=x.getXPos();
    XD_Model=x.getXMElement().getXDPosition();
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
    if (!"E37CFD1A111C3432D279588E711C3CFB0794D275EF50756A15A1D5D158B0BE24".equals(
      x.getXMElement().getDigest())) { //incompatible element model
      throw new org.xdef.sys.SRuntimeException(
        org.xdef.msg.XDEF.XDEF374);
    }
  }
  public static final String XD_NAME="Residents";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "Residents";
  private String XD_NamespaceURI;
  private int XD_Index = -1;
  private int XD_ndx;
  private String XD_XPos;
  private String XD_Model="C#Residents";
  @Override
  public void xSetText(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public org.xdef.component.XComponent xCreateXChild(org.xdef.proc.XXNode x){return new Resident(this, x);}
  @Override
  public void xAddXChild(org.xdef.component.XComponent x) {
    x.xSetNodeIndex(XD_ndx++);
    listOfResident().add((Resident) x); //C#Residents/Resident
  }
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
@SuppressWarnings("unchecked")
public static class Resident implements org.xdef.component.XComponent {
  public String getFirstName() {return _FirstName;}
  public String getLastName() {return _LastName;}
  public String getAddress() {return _Address;}
  public void setFirstName(String x) {_FirstName=x;}
  public void setLastName(String x) {_LastName=x;}
  public void setAddress(String x) {_Address=x;}
  public String xposOfGivenName(){return XD_XPos+"/@GivenName";}
  public String xposOfFamilyName(){return XD_XPos+"/@FamilyName";}
  public String xposOfAddress(){return XD_XPos+"/@Address";}
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  private String XD_Name_FirstName="GivenName";
  private String _FirstName;
  private String XD_Name_LastName="FamilyName";
  private String _LastName;
  private String XD_Name_Address="Address";
  private String _Address;
  @Override
  public Object toXon() {return org.xdef.component.XComponentUtil.toXon(this);}
  @Override
  public org.w3c.dom.Element toXml()
    {return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
    String name, String ns, String xdPos) {
    XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return 0;}
  public static final byte XON = 0;
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
    return new java.util.ArrayList<>();
  }
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
    org.w3c.dom.Element el;
    if (doc==null) {
      doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,XD_NodeName,null);
      el = doc.getDocumentElement();
    } else {
      el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
    }
    if (getFirstName() != null)
      el.setAttribute(XD_Name_FirstName, getFirstName());
    if (getLastName() != null)
      el.setAttribute(XD_Name_LastName, getLastName());
    if (getAddress() != null)
      el.setAttribute(XD_Name_Address, getAddress());
    return el;
  }
  public Resident() {}
  public Resident(org.xdef.component.XComponent p,
    String name, String ns, String xPos, String XDPos) {
    XD_NodeName=name; XD_NamespaceURI=ns;
    XD_XPos=xPos;
    XD_Model=XDPos;
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
  }
  public Resident(org.xdef.component.XComponent p,org.xdef.proc.XXNode x) {
    org.w3c.dom.Element el=x.getElement();
    XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
    XD_XPos=x.getXPos();
    XD_Model=x.getXMElement().getXDPosition();
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
    if (!"53C6B2C6C67DA9F30A056F438CE10413C2D572F69076F40D9459186DD455C3F5".equals(
      x.getXMElement().getDigest())) { //incompatible element model
      throw new org.xdef.sys.SRuntimeException(
        org.xdef.msg.XDEF.XDEF374);
    }
  }
  public static final String XD_NAME="Resident";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "Resident";
  private String XD_NamespaceURI;
  private int XD_Index = -1;
  private String XD_XPos;
  private String XD_Model="C#Residents/Resident";
  @Override
  public void xSetText(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x, org.xdef.XDParseResult value) {
    if (x.getXMNode().getXDPosition().endsWith("/@GivenName")) {
      XD_Name_FirstName = x.getNodeName();
      setFirstName(value.getParsedValue().isNull()? null: value.getParsedValue().toString());
    } else if (x.getXMNode().getXDPosition().endsWith("/@FamilyName")) {
      XD_Name_LastName = x.getNodeName();
      setLastName(value.getParsedValue().isNull()? null: value.getParsedValue().toString());
    } else {
      XD_Name_Address = x.getNodeName();
      setAddress(value.getParsedValue().isNull()? null: value.getParsedValue().toString());
    }
  }
  @Override
  public org.xdef.component.XComponent xCreateXChild(org.xdef.proc.XXNode x){return null;}
  @Override
  public void xAddXChild(org.xdef.component.XComponent x) {}
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
}
}