// This file was generated by cz.syntea.xdef.component.GenXComponent.
// XDPosition: "C#Person".
// Any modifications to this file will be lost upon recompilation.
package test.xdef.component;

public interface CI extends cz.syntea.xdef.component.XComponent {
  public String getFirstName();
  public void setFirstName(String x);
  public String xposOfFirstName();
  public String getLastName();
  public void setLastName(String x);
  public String xposOfLastName();
}