// This file was generated by cz.syntea.xdef.component.GenXComponent.
// XDPosition: "Y13#C".
// Any modifications to this file will be lost upon recompilation.
package test.xdef.component;

public interface Y13C extends cz.syntea.xdef.component.XComponent {
  public String geta();
  public void seta(String x);
  public String xposOfa();
}