// This file was generated by org.xdef.component.GenXComponent.
// XDPosition: "Y14#A".
// Any modifications to this file will be lost upon recompilation.
package test.xdef.component;

public interface Y14A extends org.xdef.component.XComponent {
  public String geta();
  public void seta(String x);
  public String xposOfa();
}