// This file was generated by org.xdef.component.GenXComponent.
// XDPosition: "SouborD1A#ProtokolDN".
// Any modifications to this file will be lost upon recompilation.
package test.xdef.component;
public class Z2 implements org.xdef.component.XComponent{
  public String getKodUtvaruPolicie() {return _KodUtvaruPolicie;}
  public org.xdef.sys.SDatetime getRokDN() {return _RokDN;}
  public java.util.Date dateOfRokDN(){return org.xdef.sys.SDatetime.getDate(_RokDN);}
  public java.sql.Timestamp timestampOfRokDN(){return org.xdef.sys.SDatetime.getTimestamp(_RokDN);}
  public java.util.Calendar calendarOfRokDN(){return org.xdef.sys.SDatetime.getCalendar(_RokDN);}
  public String getCisloDN() {return _CisloDN;}
  public String getCisloJednaciDN() {return _CisloJednaciDN;}
  public org.xdef.sys.SDatetime getDatumCasOznameni() {return _DatumCasOznameni;}
  public java.util.Date dateOfDatumCasOznameni(){return org.xdef.sys.SDatetime.getDate(_DatumCasOznameni);}
  public java.sql.Timestamp timestampOfDatumCasOznameni(){return org.xdef.sys.SDatetime.getTimestamp(_DatumCasOznameni);}
  public java.util.Calendar calendarOfDatumCasOznameni(){return org.xdef.sys.SDatetime.getCalendar(_DatumCasOznameni);}
  public String getNazevDN() {return _NazevDN;}
  public String getZpracovatel() {return _Zpracovatel;}
  public void setKodUtvaruPolicie(String x){_KodUtvaruPolicie=x;}
  public void setRokDN(org.xdef.sys.SDatetime x){_RokDN=x;}
  public void setRokDN(java.util.Date x){_RokDN=x==null?null:new org.xdef.sys.SDatetime(x);}
  public void setRokDN(java.sql.Timestamp x){_RokDN=x==null?null:new org.xdef.sys.SDatetime(x);}
  public void setRokDN(java.util.Calendar x){_RokDN=x==null?null:new org.xdef.sys.SDatetime(x);}
  public void setCisloDN(String x){_CisloDN=x;}
  public void setCisloJednaciDN(String x){_CisloJednaciDN=x;}
  public void setDatumCasOznameni(org.xdef.sys.SDatetime x){_DatumCasOznameni=x;}
  public void setDatumCasOznameni(java.util.Date x){_DatumCasOznameni=x==null?null:new org.xdef.sys.SDatetime(x);}
  public void setDatumCasOznameni(java.sql.Timestamp x){_DatumCasOznameni=x==null?null:new org.xdef.sys.SDatetime(x);}
  public void setDatumCasOznameni(java.util.Calendar x){_DatumCasOznameni=x==null?null:new org.xdef.sys.SDatetime(x);}
  public void setNazevDN(String x){_NazevDN=x;}
  public void setZpracovatel(String x){_Zpracovatel=x;}
  public String xposOfKodUtvaruPolicie(){return XD_XPos+"/@KodUtvaruPolicie";}
  public String xposOfRokDN(){return XD_XPos+"/@RokDN";}
  public String xposOfCisloDN(){return XD_XPos+"/@CisloDN";}
  public String xposOfCisloJednaciDN(){return XD_XPos+"/@CisloJednaciDN";}
  public String xposOfDatumCasOznameni(){return XD_XPos+"/@DatumCasOznameni";}
  public String xposOfNazevDN(){return XD_XPos+"/@NazevDN";}
  public String xposOfZpracovatel(){return XD_XPos+"/@Zpracovatel";}
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  public final static byte JSON = 0;
  @Override
  public org.w3c.dom.Element toXml()
    {return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
    String name, String ns, String xdPos) {
    XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return -1;}
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
    org.w3c.dom.Element el;
    if (doc==null) {
      doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,
        XD_NodeName, null);
      el = doc.getDocumentElement();
    } else {
      el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
      if (doc.getDocumentElement()==null) doc.appendChild(el);
    }
    if (getKodUtvaruPolicie() != null)
      el.setAttribute(XD_Name_KodUtvaruPolicie, getKodUtvaruPolicie());
    if (getRokDN() != null)
      el.setAttribute(XD_Name_RokDN, getRokDN().formatDate("yyyy"));
    if (getCisloDN() != null)
      el.setAttribute(XD_Name_CisloDN, getCisloDN());
    if (getCisloJednaciDN() != null)
      el.setAttribute(XD_Name_CisloJednaciDN, getCisloJednaciDN());
    if (getDatumCasOznameni() != null)
      el.setAttribute(XD_Name_DatumCasOznameni, getDatumCasOznameni().formatDate("d.M.yyyy H:mm"));
    if (getNazevDN() != null)
      el.setAttribute(XD_Name_NazevDN, getNazevDN());
    if (getZpracovatel() != null)
      el.setAttribute(XD_Name_Zpracovatel, getZpracovatel());
    return el;
  }
  @Override
  public Object toJson() {return org.xdef.json.JsonUtil.xmlToJson(toXml());}
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
    return new java.util.ArrayList<org.xdef.component.XComponent>();
  }
  public Z2() {}
  public Z2(org.xdef.component.XComponent p,
    String name, String ns, String xPos, String XDPos) {
    XD_NodeName=name; XD_NamespaceURI=ns;
    XD_XPos=xPos;
    XD_Model=XDPos;
    XD_Object = (XD_Parent=p)!=null ? p.xGetObject() : null;
  }
  public Z2(org.xdef.component.XComponent p,org.xdef.proc.XXNode x){
    org.w3c.dom.Element el=x.getElement();
    XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
    XD_XPos=x.getXPos();
    XD_Model=x.getXMElement().getXDPosition();
    XD_Object = (XD_Parent=p)!=null ? p.xGetObject() : null;
    if (!"AB38509992762E5A7B12437155F69376".equals(
      x.getXMElement().getDigest())) { //incompatible element model
      throw new org.xdef.sys.SRuntimeException(
        org.xdef.msg.XDEF.XDEF374);
    }
  }
  private String XD_Name_KodUtvaruPolicie="KodUtvaruPolicie";
  private String _KodUtvaruPolicie;
  private String XD_Name_RokDN="RokDN";
  private org.xdef.sys.SDatetime _RokDN;
  private String XD_Name_CisloDN="CisloDN";
  private String _CisloDN;
  private String XD_Name_CisloJednaciDN="CisloJednaciDN";
  private String _CisloJednaciDN;
  private String XD_Name_DatumCasOznameni="DatumCasOznameni";
  private org.xdef.sys.SDatetime _DatumCasOznameni;
  private String XD_Name_NazevDN="NazevDN";
  private String _NazevDN;
  private String XD_Name_Zpracovatel="Zpracovatel";
  private String _Zpracovatel;
  public static final String XD_NAME="ProtokolDN";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "ProtokolDN";
  private String XD_NamespaceURI;
  private int XD_Index = -1;
  private String XD_XPos;
  private String XD_Model="SouborD1A#ProtokolDN";
  @Override
  public void xSetText(org.xdef.proc.XXNode x,
    org.xdef.XDParseResult parseResult){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x,
    org.xdef.XDParseResult parseResult) {
    if (x.getXMNode().getXDPosition().endsWith("/@KodUtvaruPolicie")) {
      XD_Name_KodUtvaruPolicie = x.getNodeName();
      setKodUtvaruPolicie(parseResult.getParsedValue().toString());
    } else if (x.getXMNode().getXDPosition().endsWith("/@RokDN")) {
      XD_Name_RokDN = x.getNodeName();
      setRokDN(parseResult.getParsedValue().datetimeValue());
    } else if (x.getXMNode().getXDPosition().endsWith("/@CisloDN")) {
      XD_Name_CisloDN = x.getNodeName();
      setCisloDN(parseResult.getParsedValue().toString());
    } else if (x.getXMNode().getXDPosition().endsWith("/@CisloJednaciDN")) {
      XD_Name_CisloJednaciDN = x.getNodeName();
      setCisloJednaciDN(parseResult.getParsedValue().toString());
    } else if (x.getXMNode().getXDPosition().endsWith("/@DatumCasOznameni")) {
      XD_Name_DatumCasOznameni = x.getNodeName();
      setDatumCasOznameni(parseResult.getParsedValue().datetimeValue());
    } else if (x.getXMNode().getXDPosition().endsWith("/@NazevDN")) {
      XD_Name_NazevDN = x.getNodeName();
      setNazevDN(parseResult.getParsedValue().toString());
    } else {
      XD_Name_Zpracovatel = x.getNodeName();
      setZpracovatel(parseResult.getParsedValue().toString());
    }
  }
  @Override
  public org.xdef.component.XComponent xCreateXChild(
    org.xdef.proc.XXNode x)
    {return null;}
  @Override
  public void xAddXChild(org.xdef.component.XComponent x){}
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
}