package task1;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import org.xdef.sys.ArrayReporter;
import org.xdef.xml.KXmlUtils;
import org.xdef.XDDocument;
import org.xdef.XDPool;
import java.io.PrintStream;
import org.w3c.dom.Element;

public class Order1b {
    public static void main(String... args) throws ClassNotFoundException, IOException {
        // Create the file with compiled X-definition source data
        Order1b_gen.main();

        XDPool xpool;
        try ( // Read the XDPool object from the file(generated by Order1b_gen)
            ObjectInputStream in = new ObjectInputStream(new FileInputStream("task1/output/Order1b.xp"))) {
            xpool = (XDPool) in.readObject();
        }

        // Create an instance of XDDocument object (from XDPool)
        XDDocument xdoc = xpool.createXDDocument("Order");

        // Prepare the error reporter
        ArrayReporter reporter = new ArrayReporter();

        // Run validation mode (you can also try task1/input/Order_err.xml)
        Element result = xdoc.xparse("task1/input/Order.xml", reporter);

        // Check if an error was reported
        if (reporter.errorWarnings()) {
            try ( // Print errors to the file
                PrintStream ps = new PrintStream("task1/errors/Order_err.txt")) {
                reporter.printReports(ps);
            }
            System.err.println("Task1.Order1b Incorrect input data");
        } else {
            // No errors, write the processed document to the file
            KXmlUtils.writeXml("task1/output/Order.xml", result);
            System.out.println("OK, Task1.Order1b");
        }
    }
}