import java.io.File;
import java.sql.Connection;
import org.apache.derby.jdbc.EmbeddedDataSource;
import org.xdef.XDFactory;
import org.xdef.XDService;
import org.xdef.impl.code.DefContainer;
import org.xdef.impl.code.DefSQLStatement;
import org.xdef.impl.code.DefString;
import org.xdef.sys.FUtils;

/**
 * @author Trojan
 */
public class TestDB {
    public static void main(String... args) throws Exception {
        File derbyDir = new File("D:/opt/DB1");
        FUtils.deleteAll(derbyDir, true);
        String derby = derbyDir.getAbsolutePath().replace('\\', '/');
        EmbeddedDataSource dbSource = new EmbeddedDataSource();
        dbSource.setDatabaseName(derby);
        dbSource.setUser("app");
        dbSource.setPassword("blabla");
        // create a new database
        dbSource.setCreateDatabase("create");
        Connection con = dbSource.getConnection();
        con.close();
        
        String url = "jdbc:derby:" + derby;
        String user = "myself";
        String password = "blabla";
        XDService service = XDFactory.createSQLService(url, user, password);
        System.out.println(service.execute("CREATE SCHEMA BOOKS", null));
        System.out.println(service.execute(
            "CREATE TABLE BOOKS.AUTHOR (IDAUTHOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n" +
" AUTHOR VARCHAR(100) NOT NULL, PRIMARY KEY(IDAUTHOR), UNIQUE (AUTHOR))", null));
        System.out.println(service.execute(
            "CREATE TABLE BOOKS.TITLE (IDTITLE INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n" +
" TITLE VARCHAR(100) NOT NULL, ISSUED INTEGER, ISBN VARCHAR(10) NOT NULL,\n" +
" PRIMARY KEY(IDTITLE), UNIQUE (TITLE, ISBN))", null));
        System.out.println(service.execute(
            "CREATE TABLE BOOKS.TITLE_AUTHOR (IDTITLE_AUTHOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n" +
" IDAUTHOR INTEGER NOT NULL, IDTITLE INTEGER NOT NULL,\n" +
" PRIMARY KEY(IDTITLE_AUTHOR), UNIQUE (IDAUTHOR, IDTITLE),\n" +
" FOREIGN KEY (IDAUTHOR) REFERENCES BOOKS.AUTHOR(IDAUTHOR),\n" +
" FOREIGN KEY (IDTITLE) REFERENCES BOOKS.TITLE(IDTITLE))", null));
        service.close();
        service = XDFactory.createSQLService(url, user, password);
        
        System.out.println(service.execute("SELECT AUTHOR FROM BOOKS.AUTHOR WHERE BOOKS.AUTHOR.AUTHOR = ?",
            new DefString("The Last Theorem")));
    DefSQLStatement insertAuthor = (DefSQLStatement) service.prepareStatement(
        "INSERT INTO BOOKS.AUTHOR(AUTHOR) VALUES (?)");
    DefSQLStatement insertTitle = (DefSQLStatement) service.prepareStatement(
      "INSERT INTO BOOKS.TITLE(TITLE,ISBN,ISSUED) VALUES (?,?,?)");
    DefSQLStatement insertTitleAuthor = (DefSQLStatement) service.prepareStatement(
      "INSERT INTO BOOKS.TITLE_AUTHOR(IDAUTHOR,IDTITLE)\n"+
         "VALUES ((SELECT IDAUTHOR FROM BOOKS.AUTHOR WHERE AUTHOR=?),\n"+
         "(SELECT IDTITLE FROM BOOKS.TITLE WHERE TITLE=?))");
   DefContainer c = new DefContainer();
   c.addXDItem("The Last Theorem");
   c.addXDItem("234567819");
   c.addXDItem("1968");
   System.out.println(insertTitle.execute(c).getClass());
        System.out.println(service.execute("SELECT AUTHOR FROM BOOKS.AUTHOR WHERE BOOKS.AUTHOR.AUTHOR = ?",
            new DefString("The Last Theorem")));
//        System.out.println(service.execute("Select * from BOOKS Where TABLE_TYPE ='BASE TABLE'", null));
//        System.out.println(service.execute("Select * from BOOKS", null));
        service.close();
    }
}