// This file was generated by org.xdef.component.GenXComponent.
// X-position: "Statuses#Statuses".
// Any modifications to this file will be lost upon recompilation.
package bugreports;

public interface Mates_Statuses_I extends org.xdef.component.XComponent {
  public Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$item getjx$item();
  public void setjx$item(Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$item x);
  public String get$Status();
  public void set$Status(String x);
  public Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$item_1 getjx$item_1();
  public void setjx$item_1(Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$item_1 x);
  public String get$ActionCode();
  public void set$ActionCode(String x);
  public Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$item_2 getjx$item_2();
  public void setjx$item_2(Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$item_2 x);
  public String get$TimeOverStep();
  public void set$TimeOverStep(String x);
  public Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$item_3 getjx$item_3();
  public void setjx$item_3(Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$item_3 x);
  public String get$ChangeLog();
  public void set$ChangeLog(String x);
  public Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$array getjx$array();
  public void setjx$array(Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$array x);
  public Mates_SynPLscript.jx$map.jx$array_4.jx$map_1.jx$array get$Events();
}