// This file was generated by org.xdef.component.GenXComponent.
// X-position: "#a".
// Any modifications to this file will be lost upon recompilation.
package bugreports;
public class MyTestX_Hexb64 implements org.xdef.component.XComponent{
  public MyTestX_Hexb64.jx$item getjx$item() {return _jx$item;}
  public byte[] get$item(){
    return _jx$item==null? null: _jx$item.getval();
  }
  public MyTestX_Hexb64.jx$item_1 getjx$item_1() {return _jx$item_1;}
  public byte[] get$item_1(){
    return _jx$item_1==null? null: _jx$item_1.getval();
  }
  public java.util.List<Object> getArray$() {return toXon();}
  public void setjx$item(MyTestX_Hexb64.jx$item x) {_jx$item=x;}
  public void set$item(byte[] x){
    if(x==null) _jx$item=null; else {
      if(_jx$item==null) setjx$item(new MyTestX_Hexb64.jx$item());
      _jx$item.setval(x);
    }
  }
  public void setjx$item_1(MyTestX_Hexb64.jx$item_1 x) {_jx$item_1=x;}
  public void set$item_1(byte[] x){
    if(x==null) _jx$item_1=null; else {
      if(_jx$item_1==null) setjx$item_1(new MyTestX_Hexb64.jx$item_1());
      _jx$item_1.setval(x);
    }
  }
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  private MyTestX_Hexb64.jx$item _jx$item;
  private MyTestX_Hexb64.jx$item_1 _jx$item_1;
  @Override
  public java.util.List<Object> toXon(){
    return org.xdef.component.XComponentUtil.toXonArray(this);
  }
  @Override
  public org.w3c.dom.Element toXml()
    {return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
    String name, String ns, String xdPos) {
    XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return -1;}
  public final static byte XON = 1;
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
    java.util.List<org.xdef.component.XComponent> a=
      new java.util.ArrayList<>();
    org.xdef.component.XComponentUtil.addXC(a, getjx$item());
    org.xdef.component.XComponentUtil.addXC(a, getjx$item_1());
    return a;
  }
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
    org.w3c.dom.Element el;
    if (doc==null) {
      doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,
        XD_NodeName, null);
      el = doc.getDocumentElement();
    } else {
      el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
      if (doc.getDocumentElement()==null) doc.appendChild(el);
    }
    for (org.xdef.component.XComponent x: xGetNodeList())
      el.appendChild(x.toXml(doc));
    return el;
  }
  private static byte[] decodeBase64(String s) {
    try {
      return org.xdef.sys.SUtils.decodeBase64(
      
s.startsWith("\"")&&s.endsWith("\"")?s.substring(1, s.length() -1):s);
    } catch (org.xdef.sys.SException ex) {
      throw new org.xdef.sys.SRuntimeException(ex.getReport());
    }
  }
  private static String encodeBase64(byte[] b) {
    return org.xdef.xon.XonTools.genXMLString(
      new String(org.xdef.sys.SUtils.encodeBase64(b),
      java.nio.charset.StandardCharsets.UTF_8));
  }
  private static byte[] decodeHex(String s) {
    try {
      return org.xdef.sys.SUtils.decodeHex(s);
    } catch (org.xdef.sys.SException ex) {
      throw new org.xdef.sys.SRuntimeException(ex.getReport());
    }
  }
  private static String encodeHex(byte[] b) {
    return new String(org.xdef.sys.SUtils.encodeHex(b),
      java.nio.charset.StandardCharsets.UTF_8);
  }
  public MyTestX_Hexb64() {}
  public MyTestX_Hexb64(org.xdef.component.XComponent p,
    String name, String ns, String xPos, String XDPos) {
    XD_NodeName=name; XD_NamespaceURI=ns;
    XD_XPos=xPos;
    XD_Model=XDPos;
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
  }
  public MyTestX_Hexb64(org.xdef.component.XComponent p,org.xdef.proc.XXNode x) {
    org.w3c.dom.Element el=x.getElement();
    XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
    XD_XPos=x.getXPos();
    XD_Model=x.getXMElement().getXDPosition();
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
    if (!"BAB6658B8ABE8F6588E187DA087BDAF6CF23047A522FEAAD95B1D97C26F716DD".equals(
      x.getXMElement().getDigest())) { //incompatible element model
      throw new org.xdef.sys.SRuntimeException(
        org.xdef.msg.XDEF.XDEF374);
    }
  }
  public static final String XD_NAME="a";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "jx:array";
  private String XD_NamespaceURI = "http://www.xdef.org/xon/4.0/w";
  private int XD_Index = -1;
  private int XD_ndx;
  private String XD_XPos;
  private String XD_Model="#a/jx:array";
  @Override
  public void xSetText(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public org.xdef.component.XComponent xCreateXChild(org.xdef.proc.XXNode x){
    String s = x.getXMElement().getXDPosition();
    if ("#a/jx:array/jx:item".equals(s))
      return new jx$item(this, x);
    return new jx$item_1(this, x); // #a/jx:array/jx:item[2]
  }
  @Override
  public void xAddXChild(org.xdef.component.XComponent x) {
    x.xSetNodeIndex(XD_ndx++);
    String s = x.xGetModelPosition();
    if ("#a/jx:array/jx:item".equals(s))
      setjx$item((jx$item)x);
    else
      setjx$item_1((jx$item_1)x); //#a/jx:array/jx:item[2]
  }
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
public static class jx$item implements org.xdef.component.XComponent{
  public byte[] getval() {return _val;}
  public void setval(byte[] x) {_val=x;}
  public String xposOfval(){return XD_XPos+"/@val";}
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  private String XD_Name_val="val";
  private byte[] _val;
  @Override
  public byte[] toXon() {
    Object o = getval();
    return (o instanceof org.xdef.xon.XonTools.JNull)? null
      : (byte[])o;
  }
  @Override
  public org.w3c.dom.Element toXml()
    {return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
    String name, String ns, String xdPos) {
    XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return 0;}
  public final static byte XON = 1;
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
    return new java.util.ArrayList<>();
  }
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
    org.w3c.dom.Element el;
    if (doc==null) {
      doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,
        XD_NodeName, null);
      el = doc.getDocumentElement();
    } else {
      el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
    }
    if (getval() != null)
      el.setAttribute(XD_Name_val, encodeHex(getval()));
    return el;
  }
  public jx$item() {}
  public jx$item(org.xdef.component.XComponent p,
    String name, String ns, String xPos, String XDPos) {
    XD_NodeName=name; XD_NamespaceURI=ns;
    XD_XPos=xPos;
    XD_Model=XDPos;
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
  }
  public jx$item(org.xdef.component.XComponent p,org.xdef.proc.XXNode x) {
    org.w3c.dom.Element el=x.getElement();
    XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
    XD_XPos=x.getXPos();
    XD_Model=x.getXMElement().getXDPosition();
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
    if (!"2860DA1E10337DACD2395EB17E67BE9B495888F46A7527E78AA766C01B63CC58".equals(
      x.getXMElement().getDigest())) { //incompatible element model
      throw new org.xdef.sys.SRuntimeException(
        org.xdef.msg.XDEF.XDEF374);
    }
  }
  public static final String XD_NAME="jx:item";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "jx:item";
  private String XD_NamespaceURI = "http://www.xdef.org/xon/4.0/w";
  private int XD_Index = -1;
  private String XD_XPos;
  private String XD_Model="#a/jx:array/jx:item";
  @Override
  public void xSetText(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){
    XD_Name_val = x.getNodeName();
    setval(value.getParsedValue().isNull()? null: value.getParsedValue().getBytes());
  }
  @Override
  public org.xdef.component.XComponent xCreateXChild(org.xdef.proc.XXNode x){return null;}
  @Override
  public void xAddXChild(org.xdef.component.XComponent x) {}
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
}
public static class jx$item_1 implements org.xdef.component.XComponent{
  public byte[] getval() {return _val;}
  public void setval(byte[] x) {_val=x;}
  public String xposOfval(){return XD_XPos+"/@val";}
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  private String XD_Name_val="val";
  private byte[] _val;
  @Override
  public byte[] toXon() {
    Object o = getval();
    return (o instanceof org.xdef.xon.XonTools.JNull)? null
      : (byte[])o;
  }
  @Override
  public org.w3c.dom.Element toXml()
    {return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
    String name, String ns, String xdPos) {
    XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return 1;}
  public final static byte XON = 1;
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
    return new java.util.ArrayList<>();
  }
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
    org.w3c.dom.Element el;
    if (doc==null) {
      doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,
        XD_NodeName, null);
      el = doc.getDocumentElement();
    } else {
      el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
    }
    if (getval() != null)
      el.setAttribute(XD_Name_val, encodeBase64(getval()));
    return el;
  }
  public jx$item_1() {}
  public jx$item_1(org.xdef.component.XComponent p,
    String name, String ns, String xPos, String XDPos) {
    XD_NodeName=name; XD_NamespaceURI=ns;
    XD_XPos=xPos;
    XD_Model=XDPos;
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
  }
  public jx$item_1(org.xdef.component.XComponent p,org.xdef.proc.XXNode x) {
    org.w3c.dom.Element el=x.getElement();
    XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
    XD_XPos=x.getXPos();
    XD_Model=x.getXMElement().getXDPosition();
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
    if (!"2860DA1E10337DACD2395EB17E67BE9B495888F46A7527E78AA766C01B63CC58".equals(
      x.getXMElement().getDigest())) { //incompatible element model
      throw new org.xdef.sys.SRuntimeException(
        org.xdef.msg.XDEF.XDEF374);
    }
  }
  public static final String XD_NAME="jx:item";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "jx:item";
  private String XD_NamespaceURI = "http://www.xdef.org/xon/4.0/w";
  private int XD_Index = -1;
  private String XD_XPos;
  private String XD_Model="#a/jx:array/jx:item[2]";
  @Override
  public void xSetText(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){
    XD_Name_val = x.getNodeName();
    setval(value.getParsedValue().isNull()? null: value.getParsedValue().getBytes());
  }
  @Override
  public org.xdef.component.XComponent xCreateXChild(org.xdef.proc.XXNode x){return null;}
  @Override
  public void xAddXChild(org.xdef.component.XComponent x) {}
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
}
}