// This file was generated by org.xdef.component.GenXComponent.
// X-position: "PIS_iop_common#PlatneOd".
// Any modifications to this file will be lost upon recompilation.
package bugreports;
@SuppressWarnings("unchecked")
public class PlatneOd implements bugreports.subelem.PlatneOd,org.xdef.component.XComponent {
  public org.xdef.sys.SDatetime getPlatnostOd() {return _PlatnostOd;}
  public java.util.Date dateOfPlatnostOd(){return org.xdef.sys.SDatetime.getDate(_PlatnostOd);}
  public java.sql.Timestamp timestampOfPlatnostOd(){return org.xdef.sys.SDatetime.getTimestamp(_PlatnostOd);}
  public java.util.Calendar calendarOfPlatnostOd(){return org.xdef.sys.SDatetime.getCalendar(_PlatnostOd);}
  public void setPlatnostOd(org.xdef.sys.SDatetime x) {_PlatnostOd=x;}
  public void setPlatnostOd(java.util.Date x) {_PlatnostOd=org.xdef.sys.SDatetime.createFrom(x);}
  public void setPlatnostOd(java.sql.Timestamp x) {_PlatnostOd=org.xdef.sys.SDatetime.createFrom(x);}
  public void setPlatnostOd(java.util.Calendar x) {_PlatnostOd=org.xdef.sys.SDatetime.createFrom(x);}
  public String xposOfPlatnostOd(){return XD_XPos+"/@PlatnostOd";}
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  private String XD_Name_PlatnostOd="PlatnostOd";
  private org.xdef.sys.SDatetime _PlatnostOd;
  @Override
  public Object toXon() {return org.xdef.component.XComponentUtil.toXon(this);}
  @Override
  public org.w3c.dom.Element toXml()
	{return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
	String name, String ns, String xdPos) {
	XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return -1;}
  public static final byte XON = 0;
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
	return new java.util.ArrayList<>();
  }
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
	org.w3c.dom.Element el;
	if (doc==null) {
	  doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,XD_NodeName,null);
	  el = doc.getDocumentElement();
	} else {
	  el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
	  if (doc.getDocumentElement()==null) doc.appendChild(el);
	}
	if (getPlatnostOd() != null)
	  el.setAttribute(XD_Name_PlatnostOd, getPlatnostOd().formatDate("yyyy-MM-dd[Z]"));
	return el;
  }
  public PlatneOd() {}
  public PlatneOd(org.xdef.component.XComponent p,
	String name, String ns, String xPos, String XDPos) {
	XD_NodeName=name; XD_NamespaceURI=ns;
	XD_XPos=xPos;
	XD_Model=XDPos;
	XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
  }
  public PlatneOd(org.xdef.component.XComponent p,org.xdef.proc.XXNode x) {
	org.w3c.dom.Element el=x.getElement();
	XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
	XD_XPos=x.getXPos();
	XD_Model=x.getXMElement().getXDPosition();
	XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
	if (!"16F6B4AF4497D9F739B930543CE4A797DEBC626ABCC212F98846C16C4043E3B6".equals(
	  x.getXMElement().getDigest())) { //incompatible element model
	  throw new org.xdef.sys.SRuntimeException(
		org.xdef.msg.XDEF.XDEF374);
	}
  }
  public static final String XD_NAME="PlatneOd";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "PlatneOd";
  private String XD_NamespaceURI;
  private int XD_Index = -1;
  private String XD_XPos;
  private String XD_Model="PIS_iop_common#PlatneOd";
  @Override
  public void xSetText(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){
	XD_Name_PlatnostOd = x.getNodeName();
	setPlatnostOd(value.getParsedValue().isNull()? null: value.getParsedValue().datetimeValue());
  }
  @Override
  public org.xdef.component.XComponent xCreateXChild(org.xdef.proc.XXNode x){return null;}
  @Override
  public void xAddXChild(org.xdef.component.XComponent x) {}
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
}