// This file was generated by org.xdef.component.GenXComponent.
// X-position: "A#House".
// Any modifications to this file will be lost upon recompilation.
package task6.components1;
@SuppressWarnings("unchecked")
public class House implements org.xdef.component.XComponent {
  public Integer getNum() {return _Num;}
  public String getAddress() {return _Address;}
  public java.util.List<House.Person> listOfPerson() {
    return _Person;
  }
  public void setNum(Integer x) {_Num=x;}
  public void setAddress(String x) {_Address=x;}
  public void addPerson(House.Person x) {
    if (x!=null) {
        if (x.xGetXPos()==null)
          x.xInit(this, "Person", null, "A#House/Person");
      _Person.add(x);
    }
  }
  public String xposOfNum(){return XD_XPos+"/@Num";}
  public String xposOfAddress(){return XD_XPos+"/@Address";}
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  private String XD_Name_Num="Num";
  private Integer _Num;
  private String XD_Name_Address="Address";
  private String _Address;
  private final java.util.List<House.Person> _Person=new java.util.ArrayList<>();
  @Override
  public Object toXon() {return org.xdef.component.XComponentUtil.toXon(this);}
  @Override
  public org.w3c.dom.Element toXml()
    {return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
    String name, String ns, String xdPos) {
    XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return -1;}
  public static final byte XON = 0;
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
    java.util.List<org.xdef.component.XComponent> a=new java.util.ArrayList<>();
    org.xdef.component.XComponentUtil.addXC(a, listOfPerson());
    return a;
  }
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
    org.w3c.dom.Element el;
    if (doc==null) {
      doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,XD_NodeName,null);
      el = doc.getDocumentElement();
    } else {
      el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
      if (doc.getDocumentElement()==null) doc.appendChild(el);
    }
    if (getNum() != null)
      el.setAttribute(XD_Name_Num, getNum().toString());
    if (getAddress() != null)
      el.setAttribute(XD_Name_Address, getAddress());
    for (org.xdef.component.XComponent x: xGetNodeList())
      el.appendChild(x.toXml(doc));
    return el;
  }
  public House() {}
  public House(org.xdef.component.XComponent p,
    String name, String ns, String xPos, String XDPos) {
    XD_NodeName=name; XD_NamespaceURI=ns;
    XD_XPos=xPos;
    XD_Model=XDPos;
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
  }
  public House(org.xdef.component.XComponent p,org.xdef.proc.XXNode x) {
    org.w3c.dom.Element el=x.getElement();
    XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
    XD_XPos=x.getXPos();
    XD_Model=x.getXMElement().getXDPosition();
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
    if (!"590F0586E4CB63D2EA5B04AE51CAE2D13F3366293AB876688C03EF86BA89CC02".equals(
      x.getXMElement().getDigest())) { //incompatible element model
      throw new org.xdef.sys.SRuntimeException(
        org.xdef.msg.XDEF.XDEF374);
    }
  }
  public static final String XD_NAME="House";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "House";
  private String XD_NamespaceURI;
  private int XD_Index = -1;
  private int XD_ndx;
  private String XD_XPos;
  private String XD_Model="A#House";
  @Override
  public void xSetText(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x, org.xdef.XDParseResult value) {
    if (x.getXMNode().getXDPosition().endsWith("/@Num")) {
      XD_Name_Num = x.getNodeName();
      setNum(value.getParsedValue().isNull()? null: value.getParsedValue().intValue());
    } else {
      XD_Name_Address = x.getNodeName();
      setAddress(value.getParsedValue().isNull()? null: value.getParsedValue().toString());
    }
  }
  @Override
  public org.xdef.component.XComponent xCreateXChild(org.xdef.proc.XXNode x){return new Person(this, x);}
  @Override
  public void xAddXChild(org.xdef.component.XComponent x) {
    x.xSetNodeIndex(XD_ndx++);
    listOfPerson().add((Person) x); //A#House/Person
  }
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
@SuppressWarnings("unchecked")
public static class Person implements org.xdef.component.XComponent {
  public String getFirstName() {return _FirstName;}
  public String getLastName() {return _LastName;}
  public void setFirstName(String x) {_FirstName=x;}
  public void setLastName(String x) {_LastName=x;}
  public String xposOfFirstName(){return XD_XPos+"/@FirstName";}
  public String xposOfLastName(){return XD_XPos+"/@LastName";}
//<editor-fold defaultstate="collapsed" desc="Implementation of XComponent interface">
  private String XD_Name_FirstName="FirstName";
  private String _FirstName;
  private String XD_Name_LastName="LastName";
  private String _LastName;
  @Override
  public Object toXon() {return org.xdef.component.XComponentUtil.toXon(this);}
  @Override
  public org.w3c.dom.Element toXml()
    {return (org.w3c.dom.Element) toXml((org.w3c.dom.Document) null);}
  @Override
  public String xGetNodeName() {return XD_NodeName;}
  @Override
  public void xInit(org.xdef.component.XComponent p,
    String name, String ns, String xdPos) {
    XD_Parent=p; XD_NodeName=name; XD_NamespaceURI=ns; XD_Model=xdPos;
  }
  @Override
  public String xGetNamespaceURI() {return XD_NamespaceURI;}
  @Override
  public String xGetXPos() {return XD_XPos;}
  @Override
  public void xSetXPos(String xpos){XD_XPos = xpos;}
  @Override
  public int xGetNodeIndex() {return XD_Index;}
  @Override
  public void xSetNodeIndex(int index) {XD_Index = index;}
  @Override
  public org.xdef.component.XComponent xGetParent() {return XD_Parent;}
  @Override
  public Object xGetObject() {return XD_Object;}
  @Override
  public void xSetObject(final Object obj) {XD_Object = obj;}
  @Override
  public String toString() {return "XComponent: "+xGetModelPosition();}
  @Override
  public String xGetModelPosition() {return XD_Model;}
  @Override
  public int xGetModelIndex() {return 0;}
  public static final byte XON = 0;
  @Override
  public java.util.List<org.xdef.component.XComponent> xGetNodeList() {
    return new java.util.ArrayList<>();
  }
  @Override
  public org.w3c.dom.Node toXml(org.w3c.dom.Document doc) {
    org.w3c.dom.Element el;
    if (doc==null) {
      doc = org.xdef.xml.KXmlUtils.newDocument(XD_NamespaceURI,XD_NodeName,null);
      el = doc.getDocumentElement();
    } else {
      el = doc.createElementNS(XD_NamespaceURI, XD_NodeName);
    }
    if (getFirstName() != null)
      el.setAttribute(XD_Name_FirstName, getFirstName());
    if (getLastName() != null)
      el.setAttribute(XD_Name_LastName, getLastName());
    return el;
  }
  public Person() {}
  public Person(org.xdef.component.XComponent p,
    String name, String ns, String xPos, String XDPos) {
    XD_NodeName=name; XD_NamespaceURI=ns;
    XD_XPos=xPos;
    XD_Model=XDPos;
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
  }
  public Person(org.xdef.component.XComponent p,org.xdef.proc.XXNode x) {
    org.w3c.dom.Element el=x.getElement();
    XD_NodeName=el.getNodeName(); XD_NamespaceURI=el.getNamespaceURI();
    XD_XPos=x.getXPos();
    XD_Model=x.getXMElement().getXDPosition();
    XD_Object = (XD_Parent=p)!=null? p.xGetObject(): null;
    if (!"9B1BA7611C43C91B7C69DB8524F66E9086BA4F720223C741B1EC9035055FBDF4".equals(
      x.getXMElement().getDigest())) { //incompatible element model
      throw new org.xdef.sys.SRuntimeException(
        org.xdef.msg.XDEF.XDEF374);
    }
  }
  public static final String XD_NAME="Person";
  private org.xdef.component.XComponent XD_Parent;
  private Object XD_Object;
  private String XD_NodeName = "Person";
  private String XD_NamespaceURI;
  private int XD_Index = -1;
  private String XD_XPos;
  private String XD_Model="A#House/Person";
  @Override
  public void xSetText(org.xdef.proc.XXNode x, org.xdef.XDParseResult value){}
  @Override
  public void xSetAttr(org.xdef.proc.XXNode x, org.xdef.XDParseResult value) {
    if (x.getXMNode().getXDPosition().endsWith("/@FirstName")) {
      XD_Name_FirstName = x.getNodeName();
      setFirstName(value.getParsedValue().isNull()? null: value.getParsedValue().toString());
    } else {
      XD_Name_LastName = x.getNodeName();
      setLastName(value.getParsedValue().isNull()? null: value.getParsedValue().toString());
    }
  }
  @Override
  public org.xdef.component.XComponent xCreateXChild(org.xdef.proc.XXNode x){return null;}
  @Override
  public void xAddXChild(org.xdef.component.XComponent x) {}
  @Override
  public void xSetAny(org.w3c.dom.Element el) {}
// </editor-fold>
}
}