package modifyposition;

import java.io.Reader;
import java.io.StringReader;
import java.util.ArrayList;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.xdef.XDDocument;
import org.xdef.XDFactory;
import org.xdef.XDPool;
import org.xdef.proc.XXNode;
import org.xdef.sys.ArrayReporter;

/**
 * @author Vaclav Trojan
 */
public class ModifyPosition {

    public static final ArrayList<String> _templates;

    static {
        // string nemo reader s templaty
        String s =
"# Toto je koment\n" +
"\n"+
"/b[@x]/c[@y]\n"+
"/b[@x]/c[@y]/d\n"+
"/b[@x]\n"+
"/b[@x]/d\n";
        try {
            _templates = ModifyPosition.genTemplates(s);
        } catch(Exception ex) {
            throw new RuntimeException("Can't create templates", ex);
        }
    }

    /** Create templates from string.
     * @param modifications string with source modifications
     * @return array with generated templates.
     * @throws Exception if an error occurs,
     */
    public static ArrayList<String> genTemplates(final String modifications) throws Exception{
        return genTemplates(new StringReader(modifications));
    }

    /** Create templates from reader.
     * @param modifications reader with source modifications
     * @return array with generated templates.
     * @throws Exception if an error occurs,
     */
    public static ArrayList<String> genTemplates(final Reader modifications) throws Exception {
        ArrayList<String> result = new ArrayList<>();
        java.io.BufferedReader bfrdr =
            new java.io.BufferedReader(modifications);
        String s;
        while ((s = bfrdr.readLine()) != null) {
            if (!(s = s.trim()).isEmpty() && !s.startsWith("#")) {
                result.add(s);
                result.add(removeIndexes(s.split("/")));
            }
        }
        return result;
    }

    private static String removeIndexes(final String[] parts) {
        String result = "";
        for (int i=1; i < parts.length; i++) {
            String s = parts[i];
            if (s.isEmpty()) {
                result += "/";
            } else {
                int ndx = s.indexOf('[');
                result += "/" + (ndx >= 0 ? s.substring(0, ndx) : s);
            }
        }
        return result;
    }

    /** Modify position ait templates.
     * @param xpos position generated by X-definition.
     * @param elem actual element with this position.
     * @param templates compiled modification templates.
     * @return transformed position.
     */
    public static String modifyXPos(final String xpos, final Element elem, final ArrayList<String> templates){
        String[] parts = xpos.split("/");
        String lastPart = null;
        if (parts.length > 0) {
            String s = parts[parts.length-1];
            if (s.startsWith("@") || s.startsWith("text(")) {
                lastPart = s.charAt(0) == '@' ? s.substring(1) : s;
                String[] oldparts = parts;
                parts = new String[parts.length-1];
                System.arraycopy(oldparts, 0, parts, 0, parts.length);
            }
        }
        String pos = removeIndexes(parts);
        int i = -1;
        String s = "";
        for (int j = templates.size() - 2; j >= 0 ; j -= 2) {
            String y = templates.get(j+1);
            if (pos.endsWith(y)) {
                if(y.length() > s.length()) {
                    i = j;
                    s = y;
                }
            }
        }
        if (i == -1) {
            return xpos;
        }
        Element e = elem;
        Node n = e;
        String result = "";
        String[] parts1 = templates.get(i).split("/");
        int j = parts1.length - 1;
        int k = parts.length - 1;
        while(n != null && j >= 0 && k >= 0) {
            if (n.getNodeType() == Node.ELEMENT_NODE) {
                String part = parts[k];
                String t = parts1[j];
                int ndx = t.indexOf('[');
                String name = ndx > 0 ? t.substring(0, ndx) : t;
                ndx = t.indexOf('@');
                String attrName = ndx > 0
                    ? t.substring(ndx+1, t.length()-1) : "";
                e = (Element) n;
                if (name.equals(n.getNodeName())) {
                    if (ndx > 0 && e.hasAttribute(attrName)) {
                        String val = '@' + attrName +
                            "=\"" + e.getAttribute(attrName) + "\"";
                        result = "/" + name + "[" + val + "]" + result;
                        if (lastPart != null && !lastPart.equals(attrName)) {
                            result += "/" + (lastPart.startsWith("text(")
                                ? lastPart : "@" + lastPart);
                        }
                    } else {
                        result = "/" + part + result;
                        if (lastPart != null) {
                            result += "/" + (lastPart.startsWith("text(")
                                    ? lastPart : "@" + lastPart);
                        }
                    }
                    j--;
                } else {
                    result = "/" + part + result;
                    if (lastPart != null) {
                        result += "/" + (lastPart.startsWith("text(")
                                ? lastPart : "@" + lastPart);
                    }
                }
                k--;
            }
            lastPart = null;
            n = n.getParentNode();
        }
        while (--k >= 0) {
            result = "/" + parts[k] + result;
        }
        return result;
    }

    /** This method is called from X-definition.
     * @param xn actual model.
     * @param c code ID.
     */
    public static void xx(XXNode xn, int c) {
        System.out.println("Code: " + c + "; Original: " + xn.getXPos());
        System.out.println("Transformed: " + modifyXPos(xn.getXPos(), xn.getElement(), _templates));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String... args) {
        String xdef =
"<xd:def xmlns:xd='http://www.xdef.org/xdef/4.1' xd:root='a' name='test'>\n" +
"<xd:declaration>\n" +
"  external method void modifyposition.ModifyPosition.xx(XXNode xn, int c);\n" +
"</xd:declaration>\n" +
"<a>\n" +
"  <b xd:script='+' x='string(); onTrue xx(1);'>\n" +
"    <c xd:script='*'\n" +
"       y='string(); onTrue xx(2);' z='? string(); onTrue xx(9)'>\n" +
"      <d xd:script='*' z='string(); onTrue xx(2);'>\n" +
"        optional string(); onTrue xx(3)\n" +
"      </d>\n" +
"    </c>\n" +
"    <d xd:script='*' z='string(); onTrue xx(2);'/>\n" +
"  </b>\n" +
"</a>\n" +
"</xd:def>";
        XDPool xp = XDFactory.compileXD(null, xdef);
        String xml =
"<a>\n" +
"  <b x='x1'>\n" +
"    <c y='t1'>\n" +
"      <d z='z1'/>\n" +
"    </c>\n" +
"    <c y='y2'/>\n" +
"  </b>\n" +
"  <b x='x2'>\n" +
"    <c y='y3'/>\n" +
"    <c y='y3' z='z'/>\n" +
"    <c y='y4'>\n" +
"      <d z='z1'>\n" +
"        z2\n" +
"      </d>\n" +
"    </c>\n" +
"  </b>\n" +
"  <b x='x3'/>\n" +
"  <b x='x4'>\n" +
"   <d z='z3'/>\n" +
"  </b>\n" +
"</a>";
        ArrayReporter reporter = new ArrayReporter();
        XDDocument xd = xp.createXDDocument("test");
        xd.xparse(xml, reporter);
        System.out.println(reporter);
    }
}